"""
This pattern was made at night at 28/09/2022 with ALexander (online).
"""

pattern = {

    'vacancy': {
        'ma': ("вакансия", "job", "work", "работа", "Компания", 'vacancy', 'https://telegra.ph/', "itjob",
               "Ищем разработчика", "ищу junior", "ищу middle", "ищу senior", "Откликнуться", "ищем"),
        'mex': ("ФИО", "my name", " готовим IT-специалистов", "ответы с собеседований",
                "Подготовим к любой понравившейся вакансии", "Подготовим к вакансии",
                "онлайн-курс", "Geekhub", "Ищу работу", "Дайджест", "Xodim", "#резюме", "аутстафф",
                "outstaff", "opentowork", "ищуработу", "преподаватель", "#apply", "Resume", "#CV", "CV",
                "lookingforajob", "вебинар", "правила чата", "онлайн-школе", "количество мест ограничено",
                "@foranalysts", "free training courses", "Ищу Работу", "Как это сделать", "@jobforjunior",
                "Шукаю работу", "xodim", "Шукаю віддалену роботу", "Каналы для", "Канал для", "ВАКАНСИЯ ЗАКРЫТА",
                "в поиске новых карьерных возможностей", "Очікування зп", "Шукаю роботу", "Открыт к новым предложениям",
                "в поиске новых карьерных", "в поиске работы", "Шукаю віддалену роботу", "Шукаю роботу",
                "Я соискатель", "Моё резюме", "Мое резюме", "My CV", "I am looking for a job")
    },

    'contacts': {
        'ma': ("@", "www.", "http:"),
        'mex': ()
    },

    'fullstack': {
        'ma': ("фулл-стек", "Rust", "FullStack", "Full-stack", "Full stack", "Java ", "Java-",
               "Chief Technical Officer", " CTO", "Golang"),
        'mex': (" UI/UX designer", "контакт до CTO", "Golang собеседований", "QA Full", "stack QA", "Kotlin",
                "Position:Backend Engineer", "Вакансия: Разработчик Android", "Вакансия : Android Developer",
                "Release Engineer", "Middle QA", "Вакансия: QA Engineer")
    },

    'frontend': {
        'ma': ("веб-разработчик", "Frontend", "Front-end", "front end", " React ", " Vue ", "Angular", "Team Lead Web",
               "Vue developer"),
        'mex': ("React as a plus", "understanding of front-end", "взаимодействие с отделом frontend", "QA Automation",
                "Test Automation Engineer", "C\\+\\+", "Position:Backend Engineer", "Вакансия: Senior PHP Developer",
                "PHP Developer", "PHP backend-разработчик", "Java developer", "Senior Backend Developer",
                "Position:IT Recruiter", "Senior C\\+\\+", "Senior C\\+\\+", "Backend engineer", "QA Engineer",
                "Python Developer", 'C\\+\\+ Qt Developer', 'Position:Backend Engineer', "Middle Ruby Developer",
                "Вакансия: Senior PHP Developer", "Sеnior Jаvа-рaзрaбoтчик", "Вакансия: Automation QA",
                "Должность: Manual QA", "Web-дизайнер (UI/UX) middle", "Laravel", 'Senior Java developer',
                "Вакансия: Java Software Developer", "HCM", "на позицию DevOps", "Senior backend", "Php developer")
    },

    'backend': {
        'ma': ("Ruby", "PHP", " .NET", "NodeJS", "Python Engineer", "#ML ", "машинному обучению", "MLOps", "ML engineer",
               "Python Developer", "Разработчик Python", "#Backend", "node.js", "Backend", "Back-end", "back end",
               "Scala", "Java", "C\\+\\+", "С\\+\\+", "C#", " PHP", "PHP разработчик", " РНР", "Laravel", "Golang",
               "dwh"),
        'mex': ("DevSecOps", " UI/UX designer", "@python_job_interview", "Data Engineer", "backend разработчиками",
                "Backend QA Engineer", "тестирования backend", "тестирование backend", "QA Automation", "QA Auto",
                "Test Automation Engineer", "опыт работы с Backend", "Manual testing", "backend ecosystem",
                "автоматизируем только backend", "SOC Analyst", "Trading Support Engineer", "Android разработчик",
                "Frontend-разработчик", "Android developer", "Вакансия: Senior QA Engineer", "JavaScript разработчика",
                "Vue-разработчика", "МОБИЛЬНЫХ РАЗРАБОТЧИКОВ", "Frontend разработчика", "ios developer",
                "Head of DevOps", "Position:IT Recruiter", "Flutter Developer", "Cloud Engineer",
                "специалиста Data Science", "Azure DevOps Engineer", "Senior DevOps", "Linux System Administrator",
                "Ищем верстальщика", "Middle qa", "Angular developer", "Vue developer", "Lead devops",
                "Devops engineer", "Middle front-end", "Middle frontend", "Middle+ front-end", "Middle+ frontend",
                "#devops", "product lead", "Ищем Frontend developer")
    },
    'pm': {
        'ma': (
            " PM.", " PM,", " PM ", "Project manager", "Project Manager", "project manager", " РМ", "Project-manager",
            "Менеджер IT проектов", "Руководитель ИТ-проект", "Product Owner", "Product Manager"),
        'mex': ("собеседование с РМ", "Вакансия: Senior PHP Developer", "product lead", "Менеджер В2В", "Manager B2B",
                "Senior Front-End Developer", "Senior Software Testing Engineer", "Sales manager", "Tech Lead",
                "Android Developer", "QA Automation (Python)", "JS developer", "Senior python", "Middle UX/UI Designer",
                "Senior .NET", "C# Engineer", "Senior QA", "QA Automation", "Senior IT Recruiter")
    },

    'mobile': {
        'ma': ("Kotlin", "Swift", "Mobile", "ios", "android", "Flutter"),
        'mex': ("Python", "T-Mobile", "Swift, is a nice to have skill", "QA Automation", "QA Auto",
                "Test Automation Engineer", "Manual testing", "заказного mobile", "Junior QA Engineer", "PHP developer",
                "Senior Product Designer (UX/UI)", "Release Engineer", "Вакансия: Backend Engineer", "UI/UX Designer",
                "Product Designer", "share_ios")
    },

    'game': {
        'ma': ("Game ", "game ", "games", "Unity", "Unreal", "Senior Gameplay Engineer", "character artist",
               "background artist", "environment artist", "concept artist", "layout 3d artist", "Game Designer"),
        'mex': ()
    },

    'designer': {
        'ma': (
            "2D", "3D", "Motion", "motion", "Designer", "designer", "Дизайнер", "дизайнер", "UX", "UI", "UX/UI",
            "UI/UX", "Product designer", "Photoshop Manager", "character artist", "background artist",
            "environment artist", "concept artist", "layout 3d artist", "Game Designer"),
        'mex': ("дизайнеры", "Artec 3D", "3D scanners", "DevOps", "Web UI", "Product manager", "Product owner",
                "из дизайнера", "из Дизайнера", "designers", "3D Unity", "3D unity", "Unity 3D",
                "Understanding UI state", "Material UI", "до UI", "Python", "Java", "Kotlin", "Swift", " C ",
                "C\\+\\+", "C#", "ObjectiveC", "React", "SoapUI", "Postman", "iOS разработчик", "Full Stack",
                "fullstack Web Developer", "Flutter Developer", "Senior Dealer", "Инженер-электронщик",
                "Marketing Manager", "Unity Dev", "C#", "SMM Specialist", "Rest Api", "SQLite", "QA Automation",
                "Senior Android  developer", "Qa engineer", "Middle Тестировщик", "Senior ios разработчик",
                "Android-разработчик", "Продакт-менеджер", "product manager", "Аналитик DWH", "Delphi", "Business Analyst",
                "QA Engineer")
    },

    'hr': {
        'ma': ("Human Resources Officer", " HR", "recruter", "кадр", "human r", "head hunter", "Кадр", "HR BP",
               "HR Бизнес-партнер", "IT Recruiter", "Recruiter"),
        'mex': ("Скрининг с HR", "я HR", "представляю кадровое агентство", "Общение с HR", "общение с HR", "HR_",
                "HRTech", "HR департамент", "SEO HR", "HR@", "Кадровое агенство", "звонок с HR ",
                "Пишите нашему HR-менеджеру", "HR-Link", "HR-Prime", "HR-у", "Контакт HR", "Связаться с HR",
                "Вакансия: Android  developer", "встреча с HRD", "HR-специалистом", "Android  developer", "Созвон с HR",
                "Frontent developer", "TeamLead Python", "Senior DevOps", "Middle devops", "Java Developer",
                "Раскадровщик", "@Recruiter", "@IraRecruiter", "разработчика BackEnd", "3D художников",
                "Вакансия: DevOps", "Data engineer", "Senior Android", "Разработчик Bitrix24", "Devops",
                "Менеджер по продажам", "Data entry", "Senior PHP Developer", "DevOps Engineer")
    },

    'analyst': {
        'ma': (
            "System Analyst", "Аналитик", "Системного аналитика", "Dats scientist", "BI Engineer", "Data Engineer",
            "#SA", "SOC Analyst", "Performance аналитик", "Маркетинг аналитик", "Старший аналитик", "Тимлид аналитики",
            "Data analyst", "Data Scientist", "Data Science", "DataScientist", "data analyst", "data scientist",
            "datascientist", "аналитик данных", "Machine Learning", "Product Analyst", "Системный аналитик",
            "системный аналитик", "Системный Аналитик", "Data Modeler"),
        'mex': ("Business Analyst", "/BA", " BA", "бизнес аналитик", " ВА", "business analyst", "Бизнес аналитик",
                "Senior Product Designer (UX/UI)", "Product manager", 'Senior Dealer', "Консультант",
                "backend engineer", "Product Manager", "QA Engineer")
    },

    'qa': {
        'ma': ("QA Lead", "QAA", " QA", "по качеству", "тестировщик", "quality assurence", "тестер",
               "Test Automation Engineer", "QA Automation", "QA Auto", "Manual testing", "mobile applications testing"),
        'mex': ("тестировщиков", "тестировщиками", "проводить QA", " и QA", "to junior", "PHP Developer",
                "Senior Product Designer (UX/UI)", "Администратор баз данных", "DBA", "Ios developer middle",
                "Менеджер В2В", "Manager B2B", "Senior front-end developer", "Frontend разработчик", "#react",
                "C\\+\\+ Gameplay Developer", "Front-end developer", "Frontend developer", "Grooming artist",
                "Backend-разработчик", "Back-end-разработчик", "Tech lead", "Go developer", "Middle ux/ui",
                "#nodejs", "Senior it recruiter")
    },

    'ba': {
        'ma': ("BI Engineer", "Бизнес-Аналитик", "#BA", " BA,", " BA ", " BA.", "Business analyst", "Business Analyst",
               "бизнес аналитик", " ВА ", "business analyst", "Бизнес аналитик", "Бизнес-аналитик"),
        'mex': ("Java Developer",)
    },

    'product': {
        'ma': (
            "PrdM", "product manager", "product owner", "Head of Core Product", " CPO", "Head of Product",
            "Product Lead", "Директор по продукту", "/CPO", " CPO"),
        'mex': ("вместе с product owner", "product designer", "Взаимодействие с Product Manager")
    },

    'devops': {
        'ma': ("DevSecOps", "инженера по информационной безопасности", "DevOps", "SRE", "Site Reliability Engineer",
               "Cloud Engineer", "DBA", "Администратор баз данных", "Linux System Administrator"),
        'mex': (" и SRE", ", DevOps,", "DevOps командой", "участвовать в DevOps", "Опыт DevOps", "участвуют в DevOps",
                "DevOps practices", "devops навыки", "DevOps tools", "Java Developer", "PHP разработчик",
                "Go разработчик", "Backend .NET Developer", "product lead", "Flutter разработчик", "Graphic designer",
                "Automation QA engineer", "Senior Java", "Sales manager", "QA  инженер", "Backend engineer", "Flutter",
                "React developer", "Системный аналитик", "Senior react developer", "Middle react developer",
                "Django", "Middle QA", "Mobile manual QA", "SeniorQA", "QA Automation (Python)", "По тестированию", "Участвуют в devops",
                "Участвовать в devops", "Участие в devops", "Copywriter", "Senior ux/ui", "Senior ui/ui", "Ruby разработчик",
                "Системный аналитик", "Senior python", "Ios разработчик", "Ios developer", "Middle ios", "Junior ios", "Senior ios",
                'QA Automation', 'Sales Enablement Specialist', 'Backend-разработчика', 'тестовые окружения',
                'ручное тестирование', 'специалистов по тестированию')
    },

    'marketing': {
        'ma': ("SMM", "Copyrighter", "SEO", "Marketer", "Маркетолог", "Marketing manager", "Менеджер по маркетингу",
               "Video Tutorial Creator", "Producer", "Lead Generation Specialist", "#leadgeneration",
               "User Acquisition"),
        'mex': ("SEO HR", "Product manager", "SEO HR", "HRBP", "Sales Manager", "Manual QA", "Product Manager")
    },

    'sales_manager': {
        'ma': ("Sales manager", "sales manager", "Sales Manager", "Менеджера по продажам", "Менеджер холодных продаж",
               "Менеджер по продажам", "менеджер_отдела_продаж"),
        'mex': ()
    },

    'junior': {
        'ma': ("trainee", "junior", "джун"),
        'mex': ("не готовы рассматривать", "джуниоров пока не рассматриваем",
                "джуниоров к сожалению пока не рассматриваем", "джуниоров, к сожалению, пока не рассматриваем",
                "Работать с junior", "Senior Sales Manager", "не рассматриваем Junior", "Required 5 to 7 Years",
                "джуниоров к сожалению пока не смотрим!", "QA Lead", "Senior QA", "Supervise junior")
    },

    'middle': {
        'ma': ("Middle", "midle", "мидл"),
        'mex': ()
    },

    'senior': {
        'ma': ("Senior", "Team lead", " CTO", "сеньер", "сеньор"),
        'mex': ()
    },

    'remote': {
        'ma': ("remote", "удаленка", "удаленная", "удаленную работу", "удалённую работу", "удаленно", "удалённо"),
        'mex': ()
    },

    'relocate': {
        'ma': ("relocate", "relocation", "релокация"),
        'mex': ()
    },

    'country': {
        'ma': (
            "Тайланд", "Латвия", "Israel", "Израиль", "Moldova", "Молдова", "Dubai", "Дубаи", "РБ", "Беларусь",
            "Белорусь", "Belarus", "Грузия", "Georgia", "Россия", "Russia", "Kazakhstan", "Казахстан", "Украина",
            "Ukraine", "Армения", "РФ", "Poland", "Польша", "Spain", "Испания", "Germany", "Германия", "Romania",
            "США", "USA", "Финляндия", "Serbia", "Lithuania", "Кипр", "Турция"),
        'mex': ()
    },

    'city': {
        'ma': ("Томск", "Рига", "Москва", "Ярославль", "Хельсинки", "Стамбул", "Санкт-Петербург", "Волгоград",
               "Екатеринбург", "Самара", "Киев", "Kyiv"),
        'mex': ()
    },
    'internship': {
        'ma': ("internship", "стажировка", "trainee"),
        'mex': ()
    },
}

params = {
    'company_hiring': ('[К,к]омпан[и,i][я,и,й][^\,"\n]{1,3}[#А-ЯA-Z][a-zA-Zа-яА-Я0-9]{2,20}[^\,"\n]{1}«{0,1}[А-ЯA-Z]{0,20}[A-ZА-Яa-zа-я]{0,20}',
                       '[C,c]ompany[^\,"\n]{1,3}[#А-ЯA-Z][a-zA-Zа-яА-Я0-9]{2,20}[^\,"\n]{1}«{0,1}[А-ЯA-Z]{0,20}[A-ZА-Яa-zа-я]{0,20}',
                       '[Р,р]аботодатель[^\,"\n]{1,3}[#А-ЯA-Z][a-zA-Zа-яА-Я0-9]{2,20}[^\,"\n]{1}«{0,1}[А-ЯA-Z]{0,20}[A-ZА-Яa-zа-я]{0,20}'),
    'country': (),
    'remote': ('[Rr]emote', '[Уу]дал[ёе][н]{1,2}[кыйоая]{0,2}', '[вВ]iддален[ийка]{0,2}', '[Гг]ибридн[ыйоеая]{0,2}',
               '[Оо]фис[\W]{1,3}[Гг\.]{0,3}[\W]{0,1}[A-ZА-Я]{1}[a-zа-я]{2,}'),
    'jobs_type': ('[Ff]ull[\W]{0,1}[Tt]ime', '[Зз]анятость[\W]{0,3}[Пп]олная', '[Пп]олная[\W]{1,3}[Зз]анятость',
                  'из офиса'),
    'english_level': ('[Ee]nglish[\W]{0,2}[A-Za-zА-Яа-я][\W]{0,3}[\d]', '[Uu]pper[\W]{0,1}intermediate', '[Ii]ntermediate', '[Pp]re[\W]{0,1}[Ii]ntermediate', '[Uu]pper'),
    'relocation': ('[Рр]елокация', 'relocation', 'relocate'),
    'country_relocation': (),
    'possibility_relocaton': ()
}

cities_pattern = {
    'Russia': (
        'Moscow', 'Москва', 'St.Petersburg', '[Сс][\W]{0,1}[Пп]етербург', '[Сс]анкт[\W]{0,1}[Пп]етербург',
        '[Ее]катеринбург', '[рР]оссия', '[Тт]омск', 'РФ', '[Уу]льяновск', 'Казань', '[Оо]мск[е]{0,1}',
        '[Тт]юмен[и]{0,1}', 'СПб'
    ),
    'Germany': ('[Гг]ермания', '[Фф]ранкфурт'),
    'others': ('г\.[^\n][\W]{0,2}[A-Za-zА-Яа-я_\-\s]{3,20}', ),
    'Estonia': ('[Tt]alli[n]{1,2}', '[Ээ]стонск[уюая]{2,3}'),
    'Latvia': ('[Rr]iga', '[Лл]атвия', ),
    'Poland': ('[Pp]oland', '[Пп]ольш[ае]{1}', '[Вв]роцлав'),
    'Bulgaria': ('[Bb]ulgaria', '[Бб]олгари[ия]{1}'),
    'Portugal': ('[Pp]ortugal', '[Пп]ортугали[ия]{1}'),
    'Spain': ('[Ss]pain', '[Ии]спани[яи]{1}'),
    'Ukraine': ('[Uu]kraine', '[Уу]краин[ае]{1}'),
    'Serbia': ('[Ss]erbia', '[Сс]ерби[ия]{1}'),
    'Armenia': ('[Aa]rmenia', '[Аа]рмени[яи]{1}'),
    'Georgia': ('[Gg]eorgia', '[Гг]рузи[ия]{1}'),
    'Kazakhstan': ('[Kk]azakhstan', '[Кк]азахстан[а]{0,1}', '[Нн]ур[\W]{0,1}[Сс]ултан'),
    'Argentina': ('[Aa]rgentina', '[Аа]ргентин[ае]{1}'),
    'Uruguay': ('[Uu]ruguay', '[Уу]ругва[йе]{1}'),
    'Colombia': ('[Cc]olombia', '[Кк]олумби[яи]{1}'),
    'Узбекистан': ('Ташкент', )
}

companies_list = [
    'Prof IT',
    'Foreshko',
    'Distate',
    'Рт Мис',
    'Рт Мис',
    'Geniusto International',
    '3Keys',
    'Amarkets',
    'AppMagic',
    'Банк Урбир',
    'Konomic',
    'Excelsior',
    'Аукционный Дом',
    'GlobalTruck IT',
    'Gameram',
    'Bell Integrator',
    'Combridge itc',
    'GS Group',
    'Series Eight',
    'Pictureworks Group',
    'NewsCatcher',
    'MonetizeMore',
    'Juni',
    'RapDev.io',
    'Mudflap',
    'Shaker',
    'Shake',
    'ReUp Education',
    'Higher Logic',
    'Bellroy',
    'Meraki',
    'Bluethumb',
    'Zeektek',
    'Professional Search Group',
    'Nova Credit',
    'AssemblyAI',
    'Weigandt Consulting',
    'HRlink',
    'Адалиск',
    'Сбер',
    'Север Авто',
    'Открытый Код',
    'Evercode Lab',
    'My Games',
    'ASH',
    'Домклик',
    'Excelsior',
    'Dcloud',
    'Perfomance',
    'Bolt',
    'Crypton Studio',
    'ProfUA',
    'DataArt dataart',
    'AGIMA',
    'PurrWeb',
    'Lockular',
    'Bloomex',
    'Waves',
    'DataArt',
    'Tinkoff',
    'Task Agency',
    'Syberry',
    'Andersen',
    'Ester Digital',
    'Selecty IT',
    'Selecty',
    'Winline',
    'ServiceNow',
    'Selecty IT',
    'Dekimo',
    'Парсек Лаб',
    'Advascale',
    'OTUS',
    'Taxes For',
    'CactusSoft',
    'Robokassa',
    'GitNation',
    'Sheverev',
    'TISS',
    'Синимекс',
    'Элоконт',
    'SpurIT',
    'SoftJet',
    'Wildberries',
    'Geomotiv',
    'ShareSpace',
    'Rebrandium web',
    'Styledna.ai',
    'Bell Integrator',
    'FundCount',
    'СОРСО-СТР',
    'Яндекс',
    'Robokassa',
    'Ennabl',
    'Selecty IT',
    'Cetra',
    'SoftTeco',
    'Atomichronica',
    'TechReactGroup',
    'Amazon',
    'Rocketech.it',
    'Selecty IT',
    'Remoby',
    'Очень Интересно',
    'Блокчейн',
    'Азбука знаний',
    'RiACT',
    'DataGo!',
    'Ailet',
    'Смарт Юнит',
    'CactusSoft',
    'SoftTeco',
    'Delta Solutions',
    'Кредит Европа Банк',
    'Gazprom-Media',
    'OTUS',
    'Pixellu',
    'NGRS',
    'SoftTeco',
    'WifiMap',
    'ORTALEX',
    'Improvado',
    'CactusSoft',
    'TopSelection',
    'TopSelection',
    'TaskAgency',
    'МТС Digital',
    'Embacy',
    'TopSelection',
    'AtsAero',
    'Финтех индустрия',
    'Систематика',
    'Task Agency',
    'IBA Group',
    'Helmes',
    'Geomotiv',
    'GloboGames',
    'Credix',
    'MMD Smart',
    'Ингосстрах',
    'AppFox',
    'Meta',
    'Виэйинтеллидженс',
    'UTORG',
    'Почта банк',
    'Brainway',
    'Antilatency',
    'СВД ВС',
    'Society of Programmers Agency',
    'CloudX',
    'SimpleSales',
    'Альфа Банк',
    'Meta',
    'IBS',
    'Тим Кук',
    'Синхро',
    'ТетраСофт',
    'Mad Devs',
    'Positive Technologies',
    'Webinar',
    'Мирадор',
    'Darwin Tech Labs',
    'MMD Smart',
    'Remoby',
    'Ртим',
    'Meta',
    'Интерсвязь',
    'Evolution',
    'Mimesis Inc',
    'ITFB Group',
    'BufferGrou',
    'РСХБ Интех',
    'URSiP',
    'Exness',
    'СберМаркет',
    'Soft Jet',
    'Soft Jet',
    'Super Protocol',
    'OZON',
    'Forest Valley',
    'Society of Programmers Agency',
    'DZSystems',
    'Mir Plat.Form',
    'Codex Optimus',
    'Scout24',
    'Meta',
    'Феникс-Групп',
    'Click',
    '3KNET',
    'Star-staff',
    'Soft Jet',
    'Creative',
    'AppFox',
    'Meta',
    'EnjoyPRO',
    'Profua',
    'Agoda',
    'Meta',
    'IBS',
    'TORIBIO TECH SRL',
    'КСК эксперт',
    'Meta',
    'Meta',
    'Center-Game',
    'Tax Free',
    'FNTASTIC',
    'Bell Integrator',
    'PlayFlock',
    'Конфитрейд',
    'Transition Technologies',
    'Rho AI',
    'Transition Technologies',
    'Transition Technologies',
    'Meta',
    'Интерсвязь',
    'Aldo | Austin, TX',
    'Maxilect',
    'Meta',
    'Geomotiv',
    'KEMBERTON HEALTHCARE SERVICES LLC',
    'Washington Technology Industry Association',
    'Mission Cloud Services',
    'Center Pixel',
    'Iron Forge Development',
    'Exness',
    'Конфитрейд',
    'ДОМ.РФ',
    'Демедиа',
    'Benefactory',
    'AppFox',
    'AppFox',
    'Ртим',
    'Ртим',
    'Aston',
    'Limavi',
    'Nox',
    'Rush Agency',
    'Garpix',
    'Superdao.co',
    'Геном.Эксперт',
    'ZenBit',
    'Greenmesh',
    'Payme',
    'СенамаСофт',
    'Pivotics',
    'Pivotics',
    'ЗащитаИнфо Транс',
    'КСК эксперт',
    'SmartBrain.io',
    'ORCA.codes',
    'Bracket',
    'Zazmic Inc',
    'Polygant',
    'Meta',
    'Yucca.digital',
    'Группа Компаний Черкизово',
    'Yucca.digital',
    'BSL',
    'ПартКом',
    'BSL',
    'Mindall',
    'BetBoom',
    'Gcompany',
    'Оrmatek',
    'MarketPapa',
    'SNDGroup',
    'Softmedialab',
    'Виэйинтеллидженс',
    'SoftTeco',
    'Payme',
    'Meta',
    'CV Recruitment',
    'TalkBank',
    'Game Industry',
    'Next Games',
    'Hello, Doc!',
    'Global Career',
    'Bitlica inc',
    'Society of Programmers Agency',
    'Leidos',
    'Transition Technologies',
    'Transition Technologies',
    'Neybox Digital',
    'Marketing for Change Co',
    'CircleLink Health',
    'Leidos',
    'ProShop',
    'Webbee',
    'SAPRUN',
    'Gcompany',
    'МТС BigData',
    'PlayFlock',
    'Синхро',
    'Sheverev',
    'Синхро',
    'ЗащитаИнфо Транс',
    'Selecty',
    'Bell Integrator',
    'DynamicSun',
    'Техно Диасофт',
    'Task Agency',
    'Bell Integrator',
    'Medical Licencing',
    'Medical Licencing',
    'Centicore',
    'Программные решения плюс',
    'Toimi',
    'Task Agency',
    'Neon EVM',
    'Star-Staff',
    'Videoseed',
    'Emerging Travel Group',
    'Antilatency',
    'Task Agency',
    'Ethplorer.io',
    'Nitka Technologies',
    'DocsInBox',
    'Selecty IT',
    'Selecty IT',
    'PITBel Group',
    'DevHunt',
    'Wisercat',
    'ColorNew',
    'SenamaSoft',
    'Artezio',
    'FinCube',
    'Lea Soft',
    'ЕМС-М',
    'GrowFood',
    'Elinext',
    'ЕМС-М',
    'ORIGINS_DIGITAL',
    'Elinext',
    'HeadFinder',
    'ДНК',
    'Elinext',
    'PMP TECH',
    'Geomotiv',
    'Greenmesh',
    'Zenbit',
    'HelviX GmbH',
    'Profua',
    'OTUS',
    'Super Dispatch',
    'Dayl Group',
    'Читай-Город — Буквоед',
    'Prosper Marketplace',
    'Prosper Marketplace',
    'Keep Calm',
    'Zborka labs',
    'Xenna',
    'Atomichronica',
    'Profua',
    'Zenbit',
    'HashEx',
    'Nexters',
    'SimpleSales',
    'Upstairs',
    'Kaller',
    'Aggregion',
    'Novartis',
    'Maxar Technologies',
    'Laserfiche',
    'Leidos',
    'Amazon Dev Center',
    'Gallium Studios',
    'Sagitec',
    'Wheel',
    'Aha!',
    'Nagarro',
    'Тинькофф',
    'IBS',
    'Devquality',
    'Сервионика',
    'Devquality',
    'NAPA AUTOMOTIVE',
    'Exness',
    'Lea Soft',
    'Agoda',
    'ReTech labs',
    'Zazmic Inc',
    'Мосгортур',
    'Ethplorer.io',
    'ATTRA',
    'Global Career',
    'Global Career',
    'Prosper Marketplace',
    'Access Softek',
    'TechHive',
    'Like Центр',
    'EDSTEIN',
    'Upstairs',
    'SoftTeco',
    'Profua',
    'Citrix',
    'Aegis Foundry',
    'Nationwide IT Services',
    'VSolvit LLC',
    'IBS',
    'IBS',
    'IBS',
    'RUSSPASS',
    'Тинькофф',
    'Крауд' ,
    'Lea Soft',
    'Pixellu',
    'Smartbrain',
    'Smartbrain',
    'Bell Integrator',
    'BullPerks',
    'Carle Health',
    'UtilityAPI',
    'Fordewind',
    'PMP Tech',
    'Ennuviz',
    'Clever Jobs',
    'Hyland Software',
]

companies_set = {
    'Helmes',
    'Открытый Код',
    'Яндекс',
    'Демедиа',
    'Evercode Lab',
    'Zborka labs',
    'ТетраСофт',
    'СВД ВС',
    'Exness',
    'Distate',
    'Ennuviz',
    'Sheverev',
    'ReUp Education',
    'Ртим',
    'Polygant',
    'Keep Calm',
    'Dekimo',
    'Prof IT',
    'OZON',
    'Банк Урбир',
    'Payme',
    'Сбер',
    'Credix',
    'Bitlica inc',
    'Soft Jet',
    'Maxilect',
    'Rocketech.it',
    'Аукционный Дом',
    'Excelsior',
    'Программные решения плюс',
    'Wheel',
    'Север Авто',
    'SoftJet',
    'SNDGroup',
    'Prosper Marketplace',
    'ShareSpace',
    '3Keys',
    'Clever Jobs',
    'AGIMA',
    'Tax Free',
    'Andersen',
    'Shaker',
    'Scout24',
    'Syberry',
    'Оrmatek',
    'Brainway',
    'Финтех индустрия',
    'Zazmic Inc',
    'SenamaSoft',
    'PMP Tech',
    'Bolt',
    'СберМаркет',
    'Robokassa',
    'Tinkoff',
    'My Games',
    'FinCube',
    'MMD Smart',
    'Darwin Tech Labs',
    'Evolution',
    'Очень Интересно',
    'Синхро',
    'Dcloud',
    'Geniusto International',
    'ZenBit',
    'DataGo!',
    'Super Dispatch',
    'ProfUA',
    'MarketPapa',
    'Elinext',
    'МТС Digital',
    'РСХБ Интех',
    'Конфитрейд',
    'Альфа Банк',
    'Positive Technologies',
    'ЗащитаИнфо Транс',
    'Series Eight',
    'Zeektek',
    'Forest Valley',
    'Juni',
    'Geomotiv',
    'Smartbrain',
    'Ингосстрах',
    'ServiceNow',
    'SpurIT',
    'Amazon Dev Center',
    'FundCount',
    'Dayl Group',
    'Antilatency',
    'Maxar Technologies',
    'HeadFinder',
    'PMP TECH',
    'Техно Диасофт',
    'Game Industry',
    'AppMagic',
    'Toimi',
    'Videoseed',
    'TechHive',
    'Profua',
    'NAPA AUTOMOTIVE',
    'Center Pixel',
    'Meraki',
    'NGRS',
    'WifiMap',
    'Leidos',
    'Gallium Studios',
    'Zenbit',
    'Крауд',
    'Neybox Digital',
    'HashEx',
    'Atomichronica',
    'BullPerks',
    'Блокчейн',
    'DZSystems',
    'BSL',
    'Nova Credit',
    'Aha!',
    'Task Agency',
    'Agoda',
    'Waves',
    'Ailet',
    'Artezio',
    'Konomic',
    'КСК эксперт',
    'Bell Integrator',
    'MonetizeMore',
    'СенамаСофт',
    'HelviX GmbH',
    'PurrWeb',
    'Lea Soft',
    'ProShop',
    'Aegis Foundry',
    'ITFB Group',
    'Кредит Европа Банк',
    'Смарт Юнит',
    'Embacy',
    'ORTALEX',
    'Rush Agency',
    'Bellroy',
    'FNTASTIC',
    'Ethplorer.io',
    'Bluethumb',
    'DevHunt',
    'Nitka Technologies',
    'Азбука знаний',
    'Mudflap',
    'Professional Search Group',
    'Gazprom-Media',
    'ORCA.codes',
    'Creative',
    'Centicore',
    'Pixellu',
    'Webinar',
    'Delta Solutions',
    'GrowFood',
    'AtsAero',
    'URSiP',
    'Nexters',
    'СОРСО-СТР',
    'Amazon',
    'CV Recruitment',
    'OTUS',
    'TechReactGroup',
    'CloudX',
    'AppFox',
    'EnjoyPRO',
    'Amarkets',
    'DataArt',
    'Softmedialab',
    'IBS',
    'Star-staff',
    'Gameram',
    'Домклик',
    'Yucca.digital',
    'Advascale',
    'CircleLink Health',
    'Upstairs',
    'Xenna',
    'Winline',
    'Читай-Город — Буквоед',
    'Emerging Travel Group',
    'Taxes For',
    'Aston',
    'Higher Logic',
    'МТС BigData',
    'Access Softek',
    'ColorNew',
    'Limavi',
    'Codex Optimus',
    'CactusSoft',
    'Rho AI',
    'Crypton Studio',
    'Global Career',
    'Novartis',
    'Pivotics',
    'DocsInBox',
    'Fordewind',
    'SimpleSales',
    'Рт Мис',
    'TopSelection',
    'Society of Programmers Agency',
    'UTORG',
    'Тим Кук',
    'Combridge itc',
    'Webbee',
    'Foreshko',
    'Адалиск',
    'Styledna.ai',
    '3KNET',
    'Hyland Software',
    'Mimesis Inc',
    'PlayFlock',
    'TISS',
    'SoftTeco',
    'Lockular',
    'Carle Health',
    'DataArt dataart',
    'Sagitec',
    'Laserfiche',
    'BetBoom',
    'Ester Digital',
    'Синимекс',
    'Garpix',
    'Super Protocol',
    'Тинькофф',
    'Meta',
    'TalkBank',
    'Mission Cloud Services',
    'Mindall',
    'RapDev.io',
    'VSolvit LLC',
    'Интерсвязь',
    'Selecty IT',
    'UtilityAPI',
    'ПартКом',
    'GS Group',
    'Bloomex',
    'Систематика',
    'Mir Plat.Form',
    'GloboGames',
    'Superdao.co',
    'Bracket',
    'Nagarro',
    'Феникс-Групп',
    'Kaller',
    'Сервионика',
    'Элоконт',
    'NewsCatcher',
    'Wisercat',
    'Star-Staff',
    'AssemblyAI',
    'ATTRA',
    'Виэйинтеллидженс',
    'Selecty',
    'Nationwide IT Services',
    'GlobalTruck IT',
    'Like Центр',
    'TORIBIO TECH SRL',
    'Washington Technology Industry Association',
    'Perfomance',
    'Ennabl',
    'Почта банк',
    'Мосгортур',
    'Iron Forge Development',
    'Benefactory',
    'Группа Компаний Черкизово',
    'Center-Game',
    'Devquality',
    'RUSSPASS',
    'ReTech labs',
    'BufferGrou',
    'Greenmesh',
    'Shake',
    'Геном.Эксперт',
    'Mad Devs',
    'Pictureworks Group',
    'SAPRUN',
    'ORIGINS_DIGITAL',
    'KEMBERTON HEALTHCARE SERVICES LLC',
    'Improvado',
    'Medical Licencing',
    'Rebrandium web',
    'GitNation',
    'Click',
    'Wildberries',
    'RiACT',
    'HRlink',
    'ДНК',
    'Transition Technologies',
    'ДОМ.РФ',
    'Next Games',
    'EDSTEIN',
    'Nox',
    'SmartBrain.io',
    'Мирадор',
    'Gcompany',
    'Remoby',
    'Aldo | Austin, TX',
    'Weigandt Consulting',
    'ASH',
    'Aggregion',
    'PITBel Group',
    'TaskAgency',
    'Cetra',
    'Hello, Doc!',
    'Парсек Лаб',
    'Neon EVM',
    'Marketing for Change Co',
    'DynamicSun',
    'ЕМС-М',
    'Citrix',
    'IBA Group',
}