# Generated by Django 5.0.1 on 2024-01-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='webFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('instrumentWorks', models.CharField(max_length=50)),
                ('whatAmount', models.CharField(max_length=50)),
                ('whatTradingStrategy', models.CharField(max_length=150)),
                ('optimalInvestmentPeriod', models.JSONField()),
                ('howToReach', models.CharField(max_length=50)),
            ],
        ),
    ]
