FROM node:16-alpine AS build

WORKDIR /app

ARG GITHUB_TOKEN
ARG GITHUB_REPO

RUN apk add --no-cache git
RUN git clone https://${GITHUB_TOKEN}@${GITHUB_REPO} .

RUN npm install
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]


