version: "3"
dotenv: [".env"]
tasks:
  docker-up:
    cmds:
      - echo "Run containers."
      - echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
      - docker compose up -d --build
  docker-down:
    cmds:
      - echo "Stop containers."
      - docker compose down
