# Generated by Django 5.0.2 on 2024-03-04 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "companies",
            },
        ),
        migrations.CreateModel(
            name="CurrentSession",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("session", models.CharField(max_length=15, unique=True)),
            ],
            options={
                "db_table": "current_session",
            },
        ),
        migrations.CreateModel(
            name="AdminVacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_name", models.CharField(blank=True, max_length=150, null=True)),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                ("body", models.CharField(blank=True, max_length=6000, null=True)),
                ("profession", models.CharField(blank=True, max_length=30, null=True)),
                ("vacancy", models.CharField(blank=True, max_length=700, null=True)),
                (
                    "vacancy_url",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("company", models.CharField(blank=True, max_length=200, null=True)),
                ("english", models.CharField(blank=True, max_length=100, null=True)),
                ("relocation", models.CharField(blank=True, max_length=100, null=True)),
                ("job_type", models.CharField(blank=True, max_length=700, null=True)),
                ("city", models.CharField(blank=True, max_length=150, null=True)),
                ("salary", models.CharField(blank=True, max_length=300, null=True)),
                ("salary_from", models.IntegerField(blank=True, null=True)),
                ("salary_to", models.IntegerField(blank=True, null=True)),
                (
                    "salary_currency",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "salary_period",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("experience", models.CharField(blank=True, max_length=700, null=True)),
                ("contacts", models.CharField(blank=True, max_length=500, null=True)),
                ("time_of_public", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agregator_link",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "sended_to_agregator",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("sub", models.CharField(blank=True, max_length=250, null=True)),
                ("tags", models.CharField(blank=True, max_length=700, null=True)),
                ("full_tags", models.CharField(blank=True, max_length=700, null=True)),
                (
                    "full_anti_tags",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "short_session_numbers",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("level", models.CharField(blank=True, max_length=70, null=True)),
                ("approved", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.currentsession",
                        to_field="session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin vacancy",
                "verbose_name_plural": "Admin vacancies",
                "db_table": "admin_last_session",
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_name", models.CharField(blank=True, max_length=150, null=True)),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                ("body", models.CharField(blank=True, max_length=6000, null=True)),
                ("profession", models.CharField(blank=True, max_length=30, null=True)),
                ("vacancy", models.CharField(blank=True, max_length=700, null=True)),
                (
                    "vacancy_url",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("company", models.CharField(blank=True, max_length=200, null=True)),
                ("english", models.CharField(blank=True, max_length=100, null=True)),
                ("relocation", models.CharField(blank=True, max_length=100, null=True)),
                ("job_type", models.CharField(blank=True, max_length=700, null=True)),
                ("city", models.CharField(blank=True, max_length=150, null=True)),
                ("salary", models.CharField(blank=True, max_length=300, null=True)),
                ("salary_from", models.IntegerField(blank=True, null=True)),
                ("salary_to", models.IntegerField(blank=True, null=True)),
                (
                    "salary_currency",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "salary_period",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("experience", models.CharField(blank=True, max_length=700, null=True)),
                ("contacts", models.CharField(blank=True, max_length=500, null=True)),
                ("time_of_public", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agregator_link",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "sended_to_agregator",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("sub", models.CharField(blank=True, max_length=250, null=True)),
                ("tags", models.CharField(blank=True, max_length=700, null=True)),
                ("full_tags", models.CharField(blank=True, max_length=700, null=True)),
                (
                    "full_anti_tags",
                    models.CharField(blank=True, max_length=700, null=True),
                ),
                (
                    "short_session_numbers",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("level", models.CharField(blank=True, max_length=70, null=True)),
                ("approved", models.CharField(blank=True, max_length=100, null=True)),
                ("closed", models.BooleanField(blank=True, null=True)),
                ("rate", models.FloatField(blank=True, null=True)),
                ("salary_from_usd_month", models.IntegerField(blank=True, null=True)),
                ("salary_to_usd_month", models.IntegerField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.currentsession",
                        to_field="session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacancy",
                "verbose_name_plural": "Vacancies",
                "db_table": "vacancies",
            },
        ),
    ]
