# Generated by Django 4.2.11 on 2024-05-02 18:09

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('body', models.CharField(blank=True, max_length=10000, null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('vacancy', models.CharField(blank=True, max_length=700, null=True)),
                ('vacancy_url', models.CharField(blank=True, max_length=150, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('english', models.CharField(blank=True, max_length=100, null=True)),
                ('relocation', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(blank=True, max_length=700, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('salary', models.CharField(blank=True, max_length=300, null=True)),
                ('experience', models.CharField(blank=True, max_length=700, null=True)),
                ('contacts', models.CharField(blank=True, max_length=500, null=True)),
                ('time_of_public', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('agregator_link', models.CharField(blank=True, max_length=200, null=True)),
                ('session', models.CharField(blank=True, max_length=15, null=True)),
                ('sended_to_agregator', models.CharField(blank=True, max_length=30, null=True)),
                ('sub', models.CharField(blank=True, max_length=250, null=True)),
                ('tags', models.CharField(blank=True, max_length=700, null=True)),
                ('full_tags', models.CharField(blank=True, max_length=700, null=True)),
                ('full_anti_tags', models.CharField(blank=True, max_length=700, null=True)),
                ('short_session_numbers', models.CharField(blank=True, max_length=300, null=True)),
                ('level', models.CharField(blank=True, max_length=70, null=True)),
                ('approved', models.CharField(blank=True, max_length=150, null=True)),
                ('closed', models.BooleanField(blank=True, null=True)),
                ('salary_from', models.IntegerField(blank=True, null=True)),
                ('salary_to', models.IntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(blank=True, max_length=20, null=True)),
                ('salary_period', models.CharField(blank=True, max_length=50, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('salary_from_usd_month', models.IntegerField(blank=True, null=True)),
                ('salary_to_usd_month', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vacancies',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('added', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_admin', models.BooleanField(blank=True, null=True)),
                ('approved_gemini', models.JSONField(blank=True, null=True)),
                ('approved_filter', models.BooleanField(blank=True, null=True)),
                ('sent_to_agregator', models.IntegerField(blank=True, null=True)),
                ('full_tags', models.CharField(blank=True, max_length=200, null=True)),
                ('full_antitags', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(blank=True, null=True)),
                ('followers_total', models.IntegerField(blank=True, null=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.source')),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companies_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('vacancies_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('review_text', models.CharField(blank=True, max_length=1024, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminLastSession',
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'full_Vacancy', 'verbose_name_plural': 'full_Vacancies'},
        ),
        migrations.AlterModelTable(
            name='adminvacancy',
            table='admin_last_session',
        ),
        migrations.AddField(
            model_name='quizz',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vacancy'),
        ),
        migrations.AddField(
            model_name='filter',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vacancy'),
        ),
    ]
