# Generated by Django 4.1.4 on 2024-04-04 13:07

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_company_currentsession_adminvacancy_vacancy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "Usd"),
                            ("EUR", "Eur"),
                            ("RUB", "Rub"),
                            ("BYN", "Byn"),
                            ("KZT", "Kzt"),
                            ("PLN", "Pln"),
                            ("UAH", "Uah"),
                        ],
                        max_length=4,
                    ),
                ),
                ("rate_usd", models.FloatField(blank=True, null=True)),
                ("date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
                ("tgchannel_id", models.IntegerField(blank=True, null=True)),
                ("url", models.EmailField(blank=True, max_length=150, null=True)),
                (
                    "sourcetype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tgchannel", "Tgchannel"),
                            ("site", "Site"),
                            ("tgbot", "Tgbot"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("istarget", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Source",
                "verbose_name_plural": "Sources",
                "db_table": "sources",
            },
        ),
        migrations.AlterModelOptions(
            name="adminvacancy",
            options={
                "managed": False,
                "verbose_name": "Admin vacancy",
                "verbose_name_plural": "Admin vacancies",
            },
        ),
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Company", "verbose_name_plural": "Companies"},
        ),
        migrations.AlterModelOptions(
            name="currentsession",
            options={"managed": False},
        ),
        migrations.RemoveField(
            model_name="company",
            name="company",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="agregator_link",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="chat_name",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="rate",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="salary_from_usd_month",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="salary_to_usd_month",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="sended_to_agregator",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="session",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="short_session_numbers",
        ),
        migrations.AddField(
            model_name="company",
            name="addresses",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="background",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="company",
            name="contacts",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="contributors_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="field",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="founded",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="headquarter_address",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="company",
            name="mark",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="offices_description",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="reviewed_users",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="reviews",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="showdate",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="staff",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("аутсорсинговая", "Outsource"),
                    ("аутстаффинговая", "Outstaff"),
                    ("консалтинговая", "Consult"),
                    ("IT отдел не технической компании", "It Department"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="voted_users",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="approved_admin",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="approved_filter",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="approved_gemini",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="archive",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="company_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.company",
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="country",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="director",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="internship",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="junior",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="languages",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="lead",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="middle",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="office",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="remote",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="responded",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="senior",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="sent_to_aggregator",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="skills",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="specialization",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="tools",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="trainee",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="body",
            field=models.CharField(blank=True, max_length=10240, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="city",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="company",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="contacts",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="english",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="experience",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="full_anti_tags",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="full_tags",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="job_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("разовая", "Onetime"),
                    ("полный день", "Full"),
                    ("сокращенный день", "Shorttime"),
                    ("в свободное время", "Freetime"),
                    ("подработка", "Parttime"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="level",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="profession",
            field=models.CharField(
                blank=True,
                choices=[
                    ("developing", "Developing"),
                    ("analytics", "Analytics"),
                    ("support", "Support"),
                    ("recruting", "Recruting"),
                    ("testing", "Testing"),
                    ("design", "Design"),
                    ("management", "Management"),
                    ("security", "Security"),
                    ("content", "Content"),
                    ("marketing", "Marketing"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="relocation",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="salary",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="salary_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USD", "Usd"),
                    ("EUR", "Eur"),
                    ("RUB", "Rub"),
                    ("BYN", "Byn"),
                    ("KZT", "Kzt"),
                    ("PLN", "Pln"),
                    ("UAH", "Uah"),
                ],
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="salary_period",
            field=models.CharField(
                blank=True,
                choices=[
                    ("month", "Month"),
                    ("year", "Year"),
                    ("job", "Job"),
                    ("project", "Project"),
                    ("unit", "Unit"),
                    ("hour", "Hour"),
                    ("day", "Day"),
                    ("week", "Week"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="sub",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="tags",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="title",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="vacancy",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="vacancy_url",
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="currency_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.currency",
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="source_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.source",
            ),
        ),
    ]
